const KEY="money-data-v1",GOAL=125250;let fmt=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="profile.css?v=6"><link rel="stylesheet" href="combo.css?v=6"><link rel="stylesheet" href="board-status.css?v=6"><style>.boards{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:8px;width:100%}.boards button{width:100%;min-width:0;aspect-ratio:1/1;padding:8px 4px}.row{grid-template-columns:1fr auto auto}.historyDelete{width:38px;height:38px;align-self:center;border:1px solid #6b3038;border-radius:10px;background:#351820;color:#ff7b84;font-size:17px}@media(max-width:720px){.boards{display:flex;justify-content:flex-start}.boards button{flex:0 0 69px;min-width:69px;width:69px;aspect-ratio:1/1}}</style>');
let data={name:"",birthday:"",startDate:"",avatar:"",done:[],history:[],achievements:[],challengePartials:{},settings:{sound:true,vibration:true},birthdayShown:""},board=0,tab="challenge",modal=null,highlight=0,touchX=0,chosenAvatar="",comboResult=null,comboRequested=0,comboAttempt=0,pendingTune="";
let audioContext=null,tuneTimer=0;
const NOTES={C4:261.63,D4:293.66,E4:329.63,F4:349.23,G4:392,A4:440,B4:493.88,C5:523.25,D5:587.33,E5:659.25,F5:698.46,G5:783.99,A5:880};
function playTune(kind){if(data.settings?.sound===false)return;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;try{audioContext=audioContext||new AudioCtx;audioContext.resume();clearTimeout(tuneTimer);const birthday=[["G4",.18],["G4",.18],["A4",.36],["G4",.36],["C5",.36],["B4",.7],["G4",.18],["G4",.18],["A4",.36],["G4",.36],["D5",.36],["C5",.7],["G4",.18],["G4",.18],["G5",.36],["E5",.36],["C5",.36],["B4",.36],["A4",.7],["F5",.18],["F5",.18],["E5",.36],["C5",.36],["D5",.36],["C5",.8]],victory=[["C4",.12],["G4",.12],["C5",.2],["E5",.2],["G5",.35],["E5",.12],["G5",.12],["A5",.4],["G5",.12],["E5",.12],["C5",.2],["D5",.2],["G5",.65]],song=kind==="birthday"?birthday:victory;let at=audioContext.currentTime+.04;song.forEach(([note,d],i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=kind==="birthday"?"triangle":i%3?"square":"sawtooth";o.frequency.value=NOTES[note];g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(kind==="birthday"?.13:.09,at+.018);g.gain.exponentialRampToValueAtTime(.0001,at+d*.9);o.connect(g).connect(audioContext.destination);o.start(at);o.stop(at+d);at+=d});pendingTune=""}catch(_){pendingTune=kind}}
function requestTune(kind){pendingTune=kind;playTune(kind)}
try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&Array.isArray(x.done))data={...data,...x}}catch(e){}
const save=()=>localStorage.setItem(KEY,JSON.stringify(data)),sum=()=>data.done.reduce((a,b)=>a+b,0)+Object.values(data.challengePartials||{}).reduce((a,b)=>a+(Number(b)||0)/100,0),pct=()=>data.done.length/5,range=b=>[b*50+1,b*50+50];
const isoToday=()=>{const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
function timeline(){if(!data.startDate){data.startDate=isoToday();save()}const start=new Date(`${data.startDate}T12:00:00`),months=Math.max(0,500-data.done.length),finish=new Date(start);finish.setMonth(finish.getMonth()+months);const label=d=>d.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});return{start:label(start),finish:label(finish),months}}
const avatar=()=>data.avatar?`<span class="avatar">${data.avatar.startsWith("data:")?`<img src="${data.avatar}" alt="Foto de ${esc(data.name)}">`:data.avatar}</span>`:`<span class="avatar initial">${esc((data.name||"M")[0].toUpperCase())}</span>`;
const awardInfo={first:["Primeiro passo","Você acabou de guardar seu primeiro valor. Todo grande objetivo começa com o primeiro passo. 💚"],ten:["10 valores concluídos","Você já completou 10 números do seu desafio. Continue assim! 💰"],hundred:["100 números concluídos","Você alcançou mais uma grande etapa do Desafio dos 500. 💚"],half:["Metade do desafio","Você completou 250 dos 500 números. Faltam apenas mais 250. 💰"],complete:["Desafio completo","Você completou todos os 500 valores do desafio Money!"]};
function unlock(id,title,message){if(data.achievements.some(a=>a.id===id))return false;data.achievements.push({id,title,date:new Date().toISOString(),progress:data.done.length});save();modal={type:id==="complete"?"complete":"award",title,message};requestTune("victory");return true}
function checkAwards(n){const c=data.done.length,b=Math.floor((n-1)/50),bc=data.done.filter(x=>Math.floor((x-1)/50)===b).length,[s,e]=range(b),bt=(s+e)*25;if(c===1&&unlock("first",...awardInfo.first))return;if(c===10&&unlock("ten",...awardInfo.ten))return;if(bc===25&&unlock(`half-${b}`,`Metade do Quadro ${b+1}`,`Você chegou a 25/50 no quadro ${b+1}. Já passou da metade do caminho. 🟡`))return;if(bc===50&&unlock(`board-${b}`,`Quadro ${b+1} completo!`,`${s} a ${e} · 50/50 concluídos · ${fmt.format(bt)} guardados.`))return;if(c===100&&unlock("hundred",...awardInfo.hundred))return;if(c===250&&unlock("half",...awardInfo.half))return;if(c===500)unlock("complete",...awardInfo.complete)}
function parseMoneyInput(value){const clean=String(value).trim().replace(/[^\d,.-]/g,"");if(!clean)return 0;let normalized;if(clean.includes(","))normalized=clean.replace(/\./g,"").replace(",",".");else normalized=clean;const number=Number(normalized);return Number.isFinite(number)?Math.round(number*100):0}
function subsetLargestFirst(target,banned=0){const candidates=Array.from({length:500},(_,i)=>500-i).filter(n=>!data.done.includes(n)&&n!==banned),words=Math.ceil((target+1)/32),suffix=Array(candidates.length+1);suffix[candidates.length]=new Uint32Array(words);suffix[candidates.length][0]=1;for(let i=candidates.length-1;i>=0;i--){const source=suffix[i+1],next=source.slice(),shift=candidates[i],wordShift=shift>>>5,bitShift=shift&31;for(let w=0;w<words;w++){const bits=source[w];if(!bits)continue;const dest=w+wordShift;if(dest<words)next[dest]|=bits<<bitShift;if(bitShift&&dest+1<words)next[dest+1]|=bits>>>(32-bitShift)}suffix[i]=next}const reachable=(bits,n)=>n>=0&&!!(bits[n>>>5]&(1<<(n&31)));let best=target;while(best>0&&!reachable(suffix[0],best))best--;const numbers=[];let left=best;for(let i=0;i<candidates.length&&left>0;i++){const n=candidates[i];if(left>=n&&reachable(suffix[i+1],left-n)){numbers.push(n);left-=n}}return{numbers,total:best}}
function calculateCombination(cents,alternate=false){const available=Array.from({length:500},(_,i)=>i+1).filter(n=>!data.done.includes(n)),max=available.reduce((a,b)=>a+b,0)*100;comboRequested=cents;if(cents<=0){comboResult={error:"Informe um valor maior que zero."};render();return}if(cents>max){comboResult={error:"O valor informado é maior que o total restante do seu desafio.",max};render();return}const target=Math.floor(cents/100),previous=comboResult?.numbers||[],oldExact=comboResult?.exact;let result,banned=0;if(alternate&&previous.length){const choices=[...previous].sort((a,b)=>a-b);for(let tries=0;tries<choices.length;tries++){banned=choices[(comboAttempt+tries)%choices.length];result=subsetLargestFirst(target,banned);const exact=cents%100===0&&result.total*100===cents;if(!oldExact||exact){comboAttempt+=tries+1;break}}}if(!result)result=subsetLargestFirst(target);const totalCents=result.total*100,exact=cents%100===0&&totalCents===cents,used=new Set(result.numbers),smallestExtra=available.find(n=>!used.has(n))||0,leftover=cents-totalCents,additional=smallestExtra?Math.max(0,smallestExtra*100-leftover):0;comboResult={...result,totalCents,exact,smallestExtra,leftover,additional,banned};render()}
function applyCombination(includeExtra=false){if(!comboResult?.numbers?.length)return;const numbers=[...comboResult.numbers];if(includeExtra&&comboResult.smallestExtra&&!numbers.includes(comboResult.smallestExtra))numbers.push(comboResult.smallestExtra);const now=new Date().toISOString();for(const n of numbers.sort((a,b)=>b-a)){if(data.done.includes(n))continue;data.done.push(n);data.done.sort((a,b)=>a-b);data.history.unshift({number:n,action:"add",date:now,source:"combination"});checkAwards(n)}save();const total=numbers.reduce((a,b)=>a+b,0);comboResult=null;comboRequested=0;render();toast(`${fmt.format(total)} guardados em ${numbers.length} números! ✅`);if(data.settings.vibration&&navigator.vibrate)navigator.vibrate([35,30,35])}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){const app=document.querySelector("#app");if(!data.name){app.innerHTML=welcome();bind();return}birthday();app.innerHTML=`<main class="app"><header class="top"><img class="logo" src="icon-192.png" alt="Money"><div><h1>Money</h1><p>Desafio dos 500</p></div><button class="headAvatar" data-tab="settings" aria-label="Abrir perfil">${avatar()}</button></header>${tab==="challenge"?challenge():tab==="history"?history():tab==="stats"?stats():settings()} </main>${nav()}${modal?modalHtml():""}`;bind()}
function welcome(){return `<main class="welcome"><section class="box card"><img src="icon-192.png" alt="Money"><small class="eyebrow">SEU NOVO OBJETIVO</small><h1>Bem-vindo ao <b>Money</b></h1><p>Um passo por vez até guardar <b>${fmt.format(GOAL)}</b>.</p><form id="start"><label>Como podemos chamar você?<input name="name" required placeholder="Seu nome"></label><label>Data de nascimento<input type="date" name="birthday" required></label><div class="avatarPick"><span>Foto ou avatar (opcional)</span><div class="avatarOptions">${["🤑","😊","😎","🌟","💚"].map(x=>`<button type="button" data-avatar="${x}">${x}</button>`).join("")}</div><label class="photoBtn">Escolher foto<input id="firstPhoto" type="file" accept="image/*"></label></div><button class="primary">Começar desafio →</button></form></section></main>`}
function challenge(){const [start,end]=range(board),done=data.done.filter(n=>n>=start&&n<=end),bs=done.reduce((a,b)=>a+b,0),status=done.length===50?"complete":done.length>=25?"half":"";return `<section class="head"><small>DESAFIO DOS 500</small><h2>Olá, ${esc(data.name)}!</h2><p>Guarde valores de R$ 1,00 até R$ 500,00</p><form class="search" id="search"><input inputmode="numeric" placeholder="Buscar número (1–500)" aria-label="Buscar número"><button>⌕</button></form></section><section class="summary"><div class="tile"><span>✓ Anotados</span><b>${data.done.length}</b><small>de 500</small></div><div class="tile gold"><span>≡ Faltam</span><b>${500-data.done.length}</b><small>de 500</small></div><div class="tile"><span>● Valor guardado</span><b>${fmt.format(sum())}</b></div><div class="tile gold"><span>▰ Valor restante</span><b>${fmt.format(GOAL-sum())}</b></div></section><section class="progress card"><div><span class="eyebrow">PROGRESSO GERAL</span><strong>${pct().toFixed(2).replace(".",",")}%</strong><div class="bar"><i style="width:${pct()}%"></i></div></div><div class="ring" style="background:conic-gradient(var(--green) ${pct()}%,#293943 0)"><b>${pct().toFixed(1).replace(".",",")}%</b></div><div class="goal">Falta ${(100-pct()).toFixed(2).replace(".",",")}% <b>Meta: ${fmt.format(GOAL)}</b></div></section>${savingTool()}<section class="board card ${status}" id="board"><div class="boardhead"><button class="arrow" data-go="${board-1}" ${board===0?"disabled":""}>‹</button><div><span class="eyebrow">QUADRO ${board+1}</span><h3>${start} a ${end}</h3><small>${fmt.format(bs)} guardados · ${fmt.format(((start+end)*25)-bs)} restantes</small></div><div class="count"><b>${done.length}/50</b><small>${done.length===50?"Completo ✓":`Faltam ${50-done.length}`}</small></div><button class="arrow" data-go="${board+1}" ${board===9?"disabled":""}>›</button></div><div class="grid">${Array.from({length:50},(_,i)=>start+i).map(n=>`<button class="num ${data.done.includes(n)?"done":""} ${highlight===n?"highlight":""}" data-num="${n}">${n}</button>`).join("")}</div><p class="hint"><b>↔</b> Arraste para o lado para trocar de quadro</p></section><div class="boards">${Array.from({length:10},(_,b)=>{const [s,e]=range(b),c=data.done.filter(n=>n>=s&&n<=e).length;return `<button class="${b===board?"active":""}" data-go="${b}"><b>${b+1}</b><small>${s}–${e}<br>${c}/50</small></button>`}).join("")}</div>`}
function savingTool(){let result="";if(comboResult?.error)result=`<div class="comboResult error"><h3>Não foi possível calcular</h3><p>${comboResult.error}</p>${comboResult.max?`<b>Máximo disponível: ${fmt.format(comboResult.max/100)}</b>`:""}</div>`;else if(comboResult?.numbers){const chips=comboResult.numbers.map(n=>`<span>${fmt.format(n)}</span>`).join("<i>+</i>"),near=!comboResult.exact,canAdd=near&&comboResult.smallestExtra&&comboResult.additional>0;result=`<div class="comboResult ${near?"near":"exact"}"><span class="eyebrow">${near?"QUASE LÁ! 🎯":"ENCONTRAMOS UMA COMBINAÇÃO 🎯"}</span><h3>${near?`Melhor combinação sem ultrapassar ${fmt.format(comboRequested/100)}`:"Combinação exata encontrada"}</h3><div class="comboNumbers">${chips}</div><div class="comboTotals"><div><small>Total</small><b>${fmt.format(comboResult.totalCents/100)}</b></div><div><small>Números concluídos</small><b>${comboResult.numbers.length}</b></div></div>${near?`<p>Você ainda teria <b>${fmt.format(comboResult.leftover/100)}</b> disponíveis.</p>`:""}${canAdd?`<div class="extraTip"><span>💡</span><p>O menor número disponível depois desta combinação é <b>${fmt.format(comboResult.smallestExtra)}</b>.<br>Se adicionar <b>${fmt.format(comboResult.additional/100)}</b>, você também poderá concluí-lo. Novo total: <b>${fmt.format((comboResult.totalCents+comboResult.smallestExtra*100)/100)}</b>.</p></div>`:`<p class="priorityTip">💡 Priorizamos os maiores valores disponíveis para facilitar seu desafio no futuro.</p>`}<div class="comboActions">${near?`<button class="secondary" data-save-combo>Guardar ${fmt.format(comboResult.totalCents/100)}</button>`:`<button class="secondary" data-other-combo>Tentar outra combinação</button><button class="primary" data-save-combo>Guardar ${fmt.format(comboRequested/100)}</button>`}${canAdd?`<button class="primary" data-save-extra>Adicionar ${fmt.format(comboResult.additional/100)} e guardar ${fmt.format((comboResult.totalCents+comboResult.smallestExtra*100)/100)}</button>`:""}<button class="cancelCombo" data-cancel-combo>Cancelar</button></div></div>`}return `<section class="savingTool card"><div class="savingIntro"><div><span class="eyebrow">PLANEJADOR INTELIGENTE</span><h2>💰 Quanto você quer guardar hoje?</h2><p>Informe o valor e o Money encontra os maiores números disponíveis.</p></div><form id="comboForm"><label>Valor disponível<input id="comboValue" inputmode="decimal" placeholder="R$ 5.000,00" value="${comboRequested?fmt.format(comboRequested/100):""}"></label><button class="primary">Encontrar combinação</button></form></div>${result}</section>`}
function history(){return `<section class="pageTitle head"><small>SUA JORNADA</small><h2>Histórico</h2><p>Cada marcação é um passo mais perto da meta.</p></section><div class="list">${data.history.length?data.history.map((x,i)=>{const d=new Date(x.date);return `<article class="row card"><div><b>${x.action==="add"?"＋":"−"} ${fmt.format(x.number)}</b><span>Número ${x.number} · ${x.action==="add"?"guardado":"removido"}</span></div><time>${d.toLocaleDateString("pt-BR")}<br>${d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time><button class="historyDelete" data-history-delete="${i}" aria-label="Apagar este item do histórico">🗑</button></article>`}).join(""):`<article class="card" style="padding:50px;text-align:center"><h2>Seu histórico começa aqui</h2><p style="color:var(--muted)">Marque um número no desafio.</p></article>`}</div>`}
function stats(){const s=sum(),boards=Array.from({length:10},(_,b)=>data.done.filter(n=>Math.floor((n-1)/50)===b).length),best=Math.max(...boards),available=Array.from({length:500},(_,i)=>i+1).filter(n=>!data.done.includes(n)),next=available[0],highest=available.at(-1),time=timeline();const items=[["Início do desafio",time.start],["Previsão de término",time.finish],["Meses restantes",time.months],["Meses antecipados",data.done.length],["Concluídos",data.done.length],["Restantes",500-data.done.length],["Valor guardado",fmt.format(s)],["Valor restante",fmt.format(GOAL-s)],["Progresso",pct().toFixed(2).replace(".",",")+"%"],["Quadro mais avançado","Quadro "+(boards.indexOf(best)+1)+" · "+best+"/50"],["Quadros completos",boards.filter(x=>x===50).length],["Maior disponível",highest||"—"],["Menor disponível",next||"—"],["Média por marcação",data.done.length?fmt.format(s/data.done.length):fmt.format(0)]];const all=[["first","Primeiro passo"],["ten","10 concluídos"],["hundred","100 números"],["half","Metade do desafio"],["complete","Desafio completo"]];return `<section class="pageTitle head"><small>VISÃO GERAL</small><h2>Estatísticas</h2><p>Cada depósito antecipa sua previsão em um mês.</p></section><section class="stats">${items.map(x=>`<article class="stat card"><span>${x[0]}</span><b>${x[1]}</b></article>`).join("")}</section><section class="ach"><h2>Conquistas</h2><div>${all.map(([id,t])=>{const a=data.achievements.find(x=>x.id===id);return `<article class="card ${a?"earned":""}"><b>${a?"🏆":"🔒"} ${t}</b><span>${a?`Conquistado em ${new Date(a.date).toLocaleDateString("pt-BR")}`:"Ainda não conquistado"}</span></article>`}).join("")}${data.achievements.filter(a=>a.id.startsWith("half-")||a.id.startsWith("board-")).map(a=>`<article class="card earned"><b>🏆 ${a.title}</b><span>${new Date(a.date).toLocaleDateString("pt-BR")} às ${new Date(a.date).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></article>`).join("")}</div></section>`}
function settings(){return `<section class="profileHero">${avatar()}<h2>${esc(data.name)}</h2><p>Seu perfil Money</p></section><section class="settings card"><h3>Foto de perfil</h3><div class="avatarOptions">${["🤑","😊","😎","🌟","💚"].map(x=>`<button data-avatar="${x}">${x}</button>`).join("")}</div><label class="action" style="text-align:center;color:white">Escolher ou alterar foto<input id="profilePhoto" type="file" accept="image/*" style="display:none"></label><button class="action" id="removePhoto">Remover foto</button></section><section class="settings card"><h3>Dados pessoais</h3><label>Nome<input id="name" value="${esc(data.name)}"></label><label>Data de nascimento<input id="birthday" type="date" value="${data.birthday}"></label><button class="action" id="profile">Salvar perfil</button></section><section class="settings card"><h3>Seus dados</h3><button class="action" id="export">Baixar backup JSON</button><label class="action" style="text-align:center;color:white">Importar backup<input id="import" type="file" accept="application/json" style="display:none"></label><button class="action danger" id="reset">Reiniciar desafio</button></section>`}
function nav(){return `<nav class="nav"><button data-tab="challenge" class="${tab==="challenge"?"active":""}"><b>🎯</b>Desafio</button><button data-tab="history" class="${tab==="history"?"active":""}"><b>🕐</b>Histórico</button><button class="draw"><b>＋</b>Sortear</button><button data-tab="stats" class="${tab==="stats"?"active":""}"><b>📊</b>Estatísticas</button><button data-tab="settings" class="${tab==="settings"?"active":""}">${avatar()}<span>Perfil</span></button></nav>`}
function modalHtml(){if(modal.type==="remove")return `<div class="modalBg"><section class="modal card"><h2>Remover valor?</h2><p>Deseja remover ${fmt.format(modal.n)} do desafio?</p><div class="actions"><button data-close>Cancelar</button><button class="danger" data-remove="${modal.n}">Remover</button></div></section></div>`;if(modal.type==="draw")return `<div class="modalBg"><section class="modal card"><h2>Seu valor de hoje</h2><div class="value">${modal.n?fmt.format(modal.n):"Tudo concluído!"}</div><div class="actions"><button data-close>Cancelar</button>${modal.n?`<button class="primary" data-add="${modal.n}">Guardar</button>`:""}</div></section></div>`;const final=modal.type==="complete";return `<div class="modalBg ${final?"final":""}"><div class="confetti">${Array.from({length:28},(_,i)=>`<i style="--i:${i}"></i>`).join("")}</div><section class="modal card celebrationModal">${avatar()}<span class="eyebrow">${final?"500/500 CONCLUÍDOS":"PARABÉNS!"}</span><h2>${modal.title}</h2><div class="trophy">${final?"🏆":"🎉"}</div><p>${modal.message||modal.text}</p>${final?`<div class="value">${fmt.format(GOAL)}</div><b>Progresso: 100%</b>`:""}<button class="primary" data-close>${modal.type==="message"?"Obrigado! 💚":"Continuar"}</button></section></div>`}
function mark(n,add){data.done=add?[...data.done,n].sort((a,b)=>a-b):data.done.filter(x=>x!==n);data.history.unshift({number:n,action:add?"add":"remove",date:new Date().toISOString()});save();modal=null;if(add)checkAwards(n);render();if(add&&!modal)toast(`${fmt.format(n)} guardados! ✅`);if(add&&data.settings.vibration&&navigator.vibrate)navigator.vibrate(35)}
function birthday(){if(!data.birthday)return;const now=new Date(),b=new Date(data.birthday+"T12:00:00"),key=`${now.getFullYear()}-${now.getMonth()+1}-${now.getDate()}`;if(b.getDate()===now.getDate()&&b.getMonth()===now.getMonth()&&data.birthdayShown!==key){data.birthdayShown=key;save();modal={type:"message",title:`🎂 FELIZ ANIVERSÁRIO, ${data.name}! 🎉`,message:"Parabéns por mais um ano de vida! Que este novo ciclo seja cheio de conquistas, realizações e muitos objetivos alcançados. A equipe Money deseja um feliz aniversário! 💚"};requestTune("birthday")}}
function readPhoto(file,done){if(!file)return;const r=new FileReader;r.onload=()=>{const img=new Image;img.onload=()=>{const c=document.createElement("canvas"),s=240;c.width=c.height=s;const x=c.getContext("2d"),m=Math.min(img.width,img.height),sx=(img.width-m)/2,sy=(img.height-m)/2;x.drawImage(img,sx,sy,m,m,0,0,s,s);done(c.toDataURL("image/jpeg",.82))};img.src=r.result};r.readAsDataURL(file)}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function bind(){
  document.addEventListener("pointerdown",()=>{if(pendingTune)playTune(pendingTune)},{once:true});
  document.querySelector("#start")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);data.name=String(f.get("name")).trim();data.birthday=String(f.get("birthday"));data.startDate=isoToday();data.avatar=chosenAvatar;save();render()});
  document.querySelectorAll("[data-avatar]").forEach(x=>x.onclick=()=>{chosenAvatar=x.dataset.avatar;if(data.name){data.avatar=chosenAvatar;save();render()}else{document.querySelectorAll("[data-avatar]").forEach(b=>b.classList.toggle("selected",b===x))}});
  document.querySelector("#firstPhoto")?.addEventListener("change",e=>readPhoto(e.target.files[0],v=>{chosenAvatar=v;toast("Foto selecionada")}));
  document.querySelector("#profilePhoto")?.addEventListener("change",e=>readPhoto(e.target.files[0],v=>{data.avatar=v;save();render();toast("Foto atualizada")}));
  document.querySelector("#removePhoto")?.addEventListener("click",()=>{data.avatar="";save();render()});
  document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>{board=Math.max(0,Math.min(9,+x.dataset.go));render()});document.querySelectorAll("[data-num]").forEach(x=>x.onclick=()=>{const n=+x.dataset.num;data.done.includes(n)?(modal={type:"remove",n},render()):mark(n,true)});
  document.querySelectorAll(".boards [data-go]").forEach(x=>{const b=+x.dataset.go,[start,end]=range(b),count=data.done.filter(n=>n>=start&&n<=end).length,status=count===50?"complete":count>=25?"half":count>=1?"started":"empty";x.classList.add(`status-${status}`)});
  document.querySelectorAll("[data-history-delete]").forEach(x=>x.onclick=()=>{const i=+x.dataset.historyDelete;if(confirm("Apagar somente este item do histórico? O progresso do desafio não será alterado.")){data.history.splice(i,1);save();render();toast("Item apagado do histórico")}});
  document.querySelector(".draw")?.addEventListener("click",()=>{const a=Array.from({length:500},(_,i)=>i+1).filter(n=>!data.done.includes(n));modal={type:"draw",n:a.length?a[Math.floor(Math.random()*a.length)]:0};render()});document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{modal=null;render()});document.querySelector("[data-remove]")?.addEventListener("click",e=>mark(+e.target.dataset.remove,false));document.querySelector("[data-add]")?.addEventListener("click",e=>mark(+e.target.dataset.add,true));
  document.querySelector("#comboForm")?.addEventListener("submit",e=>{e.preventDefault();comboAttempt=0;calculateCombination(parseMoneyInput(document.querySelector("#comboValue").value))});
  document.querySelector("[data-other-combo]")?.addEventListener("click",()=>calculateCombination(comboRequested,true));
  document.querySelector("[data-save-combo]")?.addEventListener("click",()=>applyCombination(false));
  document.querySelector("[data-save-extra]")?.addEventListener("click",()=>applyCombination(true));
  document.querySelector("[data-cancel-combo]")?.addEventListener("click",()=>{comboResult=null;comboRequested=0;render()});
  document.querySelector("#search")?.addEventListener("submit",e=>{e.preventDefault();const n=+e.target.querySelector("input").value;if(n<1||n>500||!Number.isInteger(n))return toast("Digite um número de 1 a 500");board=Math.floor((n-1)/50);highlight=n;render();setTimeout(()=>{highlight=0;render()},2200)});const b=document.querySelector("#board");if(b){b.ontouchstart=e=>touchX=e.touches[0].clientX;b.ontouchend=e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45){board=Math.max(0,Math.min(9,board+(d<0?1:-1)));render()}}}
  document.querySelector("#profile")?.addEventListener("click",()=>{data.name=document.querySelector("#name").value.trim()||data.name;data.birthday=document.querySelector("#birthday").value;save();render();toast("Perfil salvo")});document.querySelector("#export")?.addEventListener("click",()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="money-backup.json";a.click();URL.revokeObjectURL(u)});document.querySelector("#import")?.addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!Array.isArray(x.done)||x.done.some(n=>n<1||n>500))throw 0;data={...data,...x,achievements:x.achievements||[]};save();render();toast("Backup importado")}catch(_){toast("Arquivo inválido")}};r.readAsText(f)});document.querySelector("#reset")?.addEventListener("click",()=>{if(confirm("Tem certeza que deseja reiniciar todo o desafio? Todos os números e o histórico serão apagados.")&&confirm("Última confirmação: reiniciar tudo?")){data.done=[];data.history=[];data.achievements=[];save();render()}})
}
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));render();
