const KEY="money-data-v1",GOAL=125250,fmt=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="profile.css"><style>.boards{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:8px;width:100%}.boards button{width:100%;min-width:0;aspect-ratio:1/1;padding:8px 4px}@media(max-width:720px){.boards{display:flex;justify-content:flex-start}.boards button{flex:0 0 69px;min-width:69px;width:69px;aspect-ratio:1/1}}</style>');
let data={name:"",birthday:"",startDate:"",avatar:"",done:[],history:[],achievements:[],settings:{sound:true,vibration:true},birthdayShown:""},board=0,tab="challenge",modal=null,highlight=0,touchX=0,chosenAvatar="";
try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&Array.isArray(x.done))data={...data,...x}}catch(e){}
const save=()=>localStorage.setItem(KEY,JSON.stringify(data)),sum=()=>data.done.reduce((a,b)=>a+b,0),pct=()=>data.done.length/5,range=b=>[b*50+1,b*50+50];
const isoToday=()=>{const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
function timeline(){if(!data.startDate){data.startDate=isoToday();save()}const start=new Date(`${data.startDate}T12:00:00`),months=Math.max(0,500-data.done.length),finish=new Date(start);finish.setMonth(finish.getMonth()+months);const label=d=>d.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});return{start:label(start),finish:label(finish),months}}
const avatar=()=>data.avatar?`<span class="avatar">${data.avatar.startsWith("data:")?`<img src="${data.avatar}" alt="Foto de ${esc(data.name)}">`:data.avatar}</span>`:`<span class="avatar initial">${esc((data.name||"M")[0].toUpperCase())}</span>`;
const awardInfo={first:["Primeiro passo","Você acabou de guardar seu primeiro valor. Todo grande objetivo começa com o primeiro passo. 💚"],ten:["10 valores concluídos","Você já completou 10 números do seu desafio. Continue assim! 💰"],hundred:["100 números concluídos","Você alcançou mais uma grande etapa do Desafio dos 500. 💚"],half:["Metade do desafio","Você completou 250 dos 500 números. Faltam apenas mais 250. 💰"],complete:["Desafio completo","Você completou todos os 500 valores do desafio Money!"]};
function unlock(id,title,message){if(data.achievements.some(a=>a.id===id))return false;data.achievements.push({id,title,date:new Date().toISOString(),progress:data.done.length});save();modal={type:id==="complete"?"complete":"award",title,message};return true}
function checkAwards(n){const c=data.done.length,b=Math.floor((n-1)/50),bc=data.done.filter(x=>Math.floor((x-1)/50)===b).length,[s,e]=range(b),bt=(s+e)*25;if(c===1&&unlock("first",...awardInfo.first))return;if(c===10&&unlock("ten",...awardInfo.ten))return;if(bc===25&&unlock(`half-${b}`,`Metade do Quadro ${b+1}`,`Você chegou a 25/50 no quadro ${b+1}. Já passou da metade do caminho. 🟡`))return;if(bc===50&&unlock(`board-${b}`,`Quadro ${b+1} completo!`,`${s} a ${e} · 50/50 concluídos · ${fmt.format(bt)} guardados.`))return;if(c===100&&unlock("hundred",...awardInfo.hundred))return;if(c===250&&unlock("half",...awardInfo.half))return;if(c===500)unlock("complete",...awardInfo.complete)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){const app=document.querySelector("#app");if(!data.name){app.innerHTML=welcome();bind();return}birthday();app.innerHTML=`<main class="app"><header class="top"><img class="logo" src="icon-192.png" alt="Money"><div><h1>Money</h1><p>Desafio dos 500</p></div><button class="headAvatar" data-tab="settings" aria-label="Abrir perfil">${avatar()}</button></header>${tab==="challenge"?challenge():tab==="history"?history():tab==="stats"?stats():settings()} </main>${nav()}${modal?modalHtml():""}`;bind()}
function welcome(){return `<main class="welcome"><section class="box card"><img src="icon-192.png" alt="Money"><small class="eyebrow">SEU NOVO OBJETIVO</small><h1>Bem-vindo ao <b>Money</b></h1><p>Um passo por vez até guardar <b>${fmt.format(GOAL)}</b>.</p><form id="start"><label>Como podemos chamar você?<input name="name" required placeholder="Seu nome"></label><label>Data de nascimento<input type="date" name="birthday" required></label><div class="avatarPick"><span>Foto ou avatar (opcional)</span><div class="avatarOptions">${["🤑","😊","😎","🌟","💚"].map(x=>`<button type="button" data-avatar="${x}">${x}</button>`).join("")}</div><label class="photoBtn">Escolher foto<input id="firstPhoto" type="file" accept="image/*"></label></div><button class="primary">Começar desafio →</button></form></section></main>`}
function challenge(){const [start,end]=range(board),done=data.done.filter(n=>n>=start&&n<=end),bs=done.reduce((a,b)=>a+b,0),status=done.length===50?"complete":done.length>=25?"half":"";return `<section class="head"><small>DESAFIO DOS 500</small><h2>Olá, ${esc(data.name)}!</h2><p>Guarde valores de R$ 1,00 até R$ 500,00</p><form class="search" id="search"><input inputmode="numeric" placeholder="Buscar número (1–500)" aria-label="Buscar número"><button>⌕</button></form></section><section class="summary"><div class="tile"><span>✓ Anotados</span><b>${data.done.length}</b><small>de 500</small></div><div class="tile gold"><span>≡ Faltam</span><b>${500-data.done.length}</b><small>de 500</small></div><div class="tile"><span>● Valor guardado</span><b>${fmt.format(sum())}</b></div><div class="tile gold"><span>▰ Valor restante</span><b>${fmt.format(GOAL-sum())}</b></div></section><section class="progress card"><div><span class="eyebrow">PROGRESSO GERAL</span><strong>${pct().toFixed(2).replace(".",",")}%</strong><div class="bar"><i style="width:${pct()}%"></i></div></div><div class="ring" style="background:conic-gradient(var(--green) ${pct()}%,#293943 0)"><b>${pct().toFixed(1).replace(".",",")}%</b></div><div class="goal">Falta ${(100-pct()).toFixed(2).replace(".",",")}% <b>Meta: ${fmt.format(GOAL)}</b></div></section><section class="board card ${status}" id="board"><div class="boardhead"><button class="arrow" data-go="${board-1}" ${board===0?"disabled":""}>‹</button><div><span class="eyebrow">QUADRO ${board+1}</span><h3>${start} a ${end}</h3><small>${fmt.format(bs)} guardados · ${fmt.format(((start+end)*25)-bs)} restantes</small></div><div class="count"><b>${done.length}/50</b><small>${done.length===50?"Completo ✓":`Faltam ${50-done.length}`}</small></div><button class="arrow" data-go="${board+1}" ${board===9?"disabled":""}>›</button></div><div class="grid">${Array.from({length:50},(_,i)=>start+i).map(n=>`<button class="num ${data.done.includes(n)?"done":""} ${highlight===n?"highlight":""}" data-num="${n}">${n}</button>`).join("")}</div><p class="hint"><b>↔</b> Arraste para o lado para trocar de quadro</p></section><div class="boards">${Array.from({length:10},(_,b)=>{const [s,e]=range(b),c=data.done.filter(n=>n>=s&&n<=e).length;return `<button class="${b===board?"active":""}" data-go="${b}"><b>${b+1}</b><small>${s}–${e}<br>${c}/50</small></button>`}).join("")}</div>`}
function history(){return `<section class="pageTitle head"><small> SUA JORNADA</small><h2>Histórico</h2><p>Cada marcação é um passo mais perto da meta.</p></section><div class="list">${data.history.length?data.history.map(x=>{const d=new Date(x.date);return `<article class="row card"><div><b>${x.action==="add"?"＋":"−"} ${fmt.format(x.number)}</b><span>Número ${x.number} · ${x.action==="add"?"guardado":"removido"}</span></div><time>${d.toLocaleDateString("pt-BR")}<br>${d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time></article>`}).join(""):`<article class="card" style="padding:50px;text-align:center"><h2>Seu histórico começa aqui</h2><p style="color:var(--muted)">Marque um número no desafio.</p></article>`}</div>`}
function stats(){const s=sum(),boards=Array.from({length:10},(_,b)=>data.done.filter(n=>Math.floor((n-1)/50)===b).length),best=Math.max(...boards),next=Array.from({length:500},(_,i)=>i+1).find(n=>!data.done.includes(n)),time=timeline();const items=[["Início do desafio",time.start],["Previsão de término",time.finish],["Meses restantes",time.months],["Meses antecipados",data.done.length],["Concluídos",data.done.length],["Restantes",500-data.done.length],["Valor guardado",fmt.format(s)],["Valor restante",fmt.format(GOAL-s)],["Progresso",pct().toFixed(2).replace(".",",")+"%"],["Quadro mais avançado","Quadro "+(boards.indexOf(best)+1)+" · "+best+"/50"],["Quadros completos",boards.filter(x=>x===50).length],["Maior concluído",data.done.length?Math.max(...data.done):"—"],["Menor disponível",next||"—"],["Média por marcação",data.done.length?fmt.format(s/data.done.length):fmt.format(0)]];const all=[["first","Primeiro passo"],["ten","10 concluídos"],["hundred","100 números"],["half","Metade do desafio"],["complete","Desafio completo"]];return `<section class="pageTitle head"><small>VISÃO GERAL</small><h2>Estatísticas</h2><p>Cada depósito antecipa sua previsão em um mês.</p></section><section class="stats">${items.map(x=>`<article class="stat card"><span>${x[0]}</span><b>${x[1]}</b></article>`).join("")}</section><section class="ach"><h2>Conquistas</h2><div>${all.map(([id,t])=>{const a=data.achievements.find(x=>x.id===id);return `<article class="card ${a?"earned":""}"><b>${a?"🏆":"🔒"} ${t}</b><span>${a?`Conquistado em ${new Date(a.date).toLocaleDateString("pt-BR")}`:"Ainda não conquistado"}</span></article>`}).join("")}${data.achievements.filter(a=>a.id.startsWith("half-")||a.id.startsWith("board-")).map(a=>`<article class="card earned"><b>🏆 ${a.title}</b><span>${new Date(a.date).toLocaleDateString("pt-BR")} às ${new Date(a.date).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></article>`).join("")}</div></section>`}
function settings(){return `<section class="profileHero">${avatar()}<h2>${esc(data.name)}</h2><p>Seu perfil Money</p></section><section class="settings card"><h3>Foto de perfil</h3><div class="avatarOptions">${["🤑","😊","😎","🌟","💚"].map(x=>`<button data-avatar="${x}">${x}</button>`).join("")}</div><label class="action" style="text-align:center;color:white">Escolher ou alterar foto<input id="profilePhoto" type="file" accept="image/*" style="display:none"></label><button class="action" id="removePhoto">Remover foto</button></section><section class="settings card"><h3>Dados pessoais</h3><label>Nome<input id="name" value="${esc(data.name)}"></label><label>Data de nascimento<input id="birthday" type="date" value="${data.birthday}"></label><button class="action" id="profile">Salvar perfil</button></section><section class="settings card"><h3>Seus dados</h3><button class="action" id="export">Baixar backup JSON</button><label class="action" style="text-align:center;color:white">Importar backup<input id="import" type="file" accept="application/json" style="display:none"></label><button class="action danger" id="reset">Reiniciar desafio</button></section>`}
function nav(){return `<nav class="nav"><button data-tab="challenge" class="${tab==="challenge"?"active":""}"><b>🎯</b>Desafio</button><button data-tab="history" class="${tab==="history"?"active":""}"><b>🕐</b>Histórico</button><button class="draw"><b>＋</b>Sortear</button><button data-tab="stats" class="${tab==="stats"?"active":""}"><b>📊</b>Estatísticas</button><button data-tab="settings" class="${tab==="settings"?"active":""}">${avatar()}<span>Perfil</span></button></nav>`}
function modalHtml(){if(modal.type==="remove")return `<div class="modalBg"><section class="modal card"><h2>Remover valor?</h2><p>Deseja remover ${fmt.format(modal.n)} do desafio?</p><div class="actions"><button data-close>Cancelar</button><button class="danger" data-remove="${modal.n}">Remover</button></div></section></div>`;if(modal.type==="draw")return `<div class="modalBg"><section class="modal card"><h2>Seu valor de hoje</h2><div class="value">${modal.n?fmt.format(modal.n):"Tudo concluído!"}</div><div class="actions"><button data-close>Cancelar</button>${modal.n?`<button class="primary" data-add="${modal.n}">Guardar</button>`:""}</div></section></div>`;const final=modal.type==="complete";return `<div class="modalBg ${final?"final":""}"><div class="confetti">${Array.from({length:28},(_,i)=>`<i style="--i:${i}"></i>`).join("")}</div><section class="modal card celebrationModal">${avatar()}<span class="eyebrow">${final?"500/500 CONCLUÍDOS":"PARABÉNS!"}</span><h2>${modal.title}</h2><div class="trophy">${final?"🏆":"🎉"}</div><p>${modal.message||modal.text}</p>${final?`<div class="value">${fmt.format(GOAL)}</div><b>Progresso: 100%</b>`:""}<button class="primary" data-close>${modal.type==="message"?"Obrigado! 💚":"Continuar"}</button></section></div>`}
function mark(n,add){data.done=add?[...data.done,n].sort((a,b)=>a-b):data.done.filter(x=>x!==n);data.history.unshift({number:n,action:add?"add":"remove",date:new Date().toISOString()});save();modal=null;if(add)checkAwards(n);render();if(add&&!modal)toast(`${fmt.format(n)} guardados! ✅`);if(add&&data.settings.vibration&&navigator.vibrate)navigator.vibrate(35)}
function birthday(){if(!data.birthday)return;const now=new Date(),b=new Date(data.birthday+"T12:00:00"),key=`${now.getFullYear()}-${now.getMonth()+1}-${now.getDate()}`;if(b.getDate()===now.getDate()&&b.getMonth()===now.getMonth()&&data.birthdayShown!==key){data.birthdayShown=key;save();modal={type:"message",title:`🎂 FELIZ ANIVERSÁRIO, ${data.name}! 🎉`,message:"Parabéns por mais um ano de vida! Que este novo ciclo seja cheio de conquistas, realizações e muitos objetivos alcançados. A equipe Money deseja um feliz aniversário! 💚"}}}
function readPhoto(file,done){if(!file)return;const r=new FileReader;r.onload=()=>{const img=new Image;img.onload=()=>{const c=document.createElement("canvas"),s=240;c.width=c.height=s;const x=c.getContext("2d"),m=Math.min(img.width,img.height),sx=(img.width-m)/2,sy=(img.height-m)/2;x.drawImage(img,sx,sy,m,m,0,0,s,s);done(c.toDataURL("image/jpeg",.82))};img.src=r.result};r.readAsDataURL(file)}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function bind(){
  document.querySelector("#start")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);data.name=String(f.get("name")).trim();data.birthday=String(f.get("birthday"));data.startDate=isoToday();data.avatar=chosenAvatar;save();render()});
  document.querySelectorAll("[data-avatar]").forEach(x=>x.onclick=()=>{chosenAvatar=x.dataset.avatar;if(data.name){data.avatar=chosenAvatar;save();render()}else{document.querySelectorAll("[data-avatar]").forEach(b=>b.classList.toggle("selected",b===x))}});
  document.querySelector("#firstPhoto")?.addEventListener("change",e=>readPhoto(e.target.files[0],v=>{chosenAvatar=v;toast("Foto selecionada")}));
  document.querySelector("#profilePhoto")?.addEventListener("change",e=>readPhoto(e.target.files[0],v=>{data.avatar=v;save();render();toast("Foto atualizada")}));
  document.querySelector("#removePhoto")?.addEventListener("click",()=>{data.avatar="";save();render()});
  document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>{board=Math.max(0,Math.min(9,+x.dataset.go));render()});document.querySelectorAll("[data-num]").forEach(x=>x.onclick=()=>{const n=+x.dataset.num;data.done.includes(n)?(modal={type:"remove",n},render()):mark(n,true)});
  document.querySelector(".draw")?.addEventListener("click",()=>{const a=Array.from({length:500},(_,i)=>i+1).filter(n=>!data.done.includes(n));modal={type:"draw",n:a.length?a[Math.floor(Math.random()*a.length)]:0};render()});document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{modal=null;render()});document.querySelector("[data-remove]")?.addEventListener("click",e=>mark(+e.target.dataset.remove,false));document.querySelector("[data-add]")?.addEventListener("click",e=>mark(+e.target.dataset.add,true));
  document.querySelector("#search")?.addEventListener("submit",e=>{e.preventDefault();const n=+e.target.querySelector("input").value;if(n<1||n>500||!Number.isInteger(n))return toast("Digite um número de 1 a 500");board=Math.floor((n-1)/50);highlight=n;render();setTimeout(()=>{highlight=0;render()},2200)});const b=document.querySelector("#board");if(b){b.ontouchstart=e=>touchX=e.touches[0].clientX;b.ontouchend=e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45){board=Math.max(0,Math.min(9,board+(d<0?1:-1)));render()}}}
  document.querySelector("#profile")?.addEventListener("click",()=>{data.name=document.querySelector("#name").value.trim()||data.name;data.birthday=document.querySelector("#birthday").value;save();render();toast("Perfil salvo")});document.querySelector("#export")?.addEventListener("click",()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="money-backup.json";a.click();URL.revokeObjectURL(u)});document.querySelector("#import")?.addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!Array.isArray(x.done)||x.done.some(n=>n<1||n>500))throw 0;data={...data,...x,achievements:x.achievements||[]};save();render();toast("Backup importado")}catch(_){toast("Arquivo inválido")}};r.readAsText(f)});document.querySelector("#reset")?.addEventListener("click",()=>{if(confirm("Tem certeza que deseja reiniciar todo o desafio? Todos os números e o histórico serão apagados.")&&confirm("Última confirmação: reiniciar tudo?")){data.done=[];data.history=[];data.achievements=[];save();render()}})
}
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));render();
